services:
  test_db:
    image: postgres:16-alpine
    container_name: snippetly-test-db
    env_file:
      - ./backend/.env.test
    ports:
      - "55432:5432"
    restart: unless-stopped

  test_redis:
    image: redis:7-alpine
    container_name: snippetly-test-redis
    command: [ "redis-server", "--appendonly", "no" ]
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 5s
      retries: 5

  test_mongodb:
    image: mongo:7-jammy
    container_name: snippetly-test-mongodb
    env_file:
      - ./backend/.env.test
    ports:
      - "27018:27017"
    command: [ "--logpath", "/dev/null", "--quiet" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 5s
      retries: 5

  test_backend:
    build:
      context: ./backend
      dockerfile: docker/test/Dockerfile
    container_name: snippetly-test-backend
    env_file:
      - ./backend/.env.test
    depends_on:
      - test_db
      - test_redis
      - test_mongodb
    command: bash -c "uv run alembic upgrade head && uv run pytest"

volumes:
  pgdata_test:

networks:
  default:
    name: snippetly-test-net
