services:
  db:
    image: postgres:16-alpine
    container_name: snippetly-db
    env_file:
      - ./backend/.env
    volumes:
      - /opt/app-data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-snippetly} -d ${POSTGRES_DB:-snippetly}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: snippetly-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - /opt/app-data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 5s
      retries: 5

  mongodb:
    image: mongo:7-jammy
    container_name: snippetly-mongodb
    env_file:
      - ./backend/.env
    volumes:
      - /opt/app-data/mongo:/data/db
    restart: unless-stopped
    command: [
      "--logpath", "/dev/null",
      "--quiet"
    ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 5s
      retries: 5

  backend:
    image: ${BACKEND_IMAGE}
    env_file:
      - ./backend/.env
    container_name: snippetly-backend
    depends_on:
      - db
      - redis
      - mongodb
    expose:
      - "8000"
    volumes:
      - ./backend/static/avatars:/app/static/avatars
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8000/api/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  migrate:
    image: ${BACKEND_IMAGE}
    container_name: snippetly-migrate
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: uv run alembic upgrade head

  celery-worker:
    image: ${BACKEND_IMAGE}
    command: uv run celery -A src.worker.app.app worker --loglevel=info
    env_file: [ ./backend/.env ]
    depends_on: [ db, redis ]
    restart: unless-stopped

  celery-beat:
    image: ${BACKEND_IMAGE}
    command: uv run celery -A src.worker.app.app beat --loglevel=info
    env_file: [ ./backend/.env ]
    depends_on: [ db, redis ]
    restart: unless-stopped
  #    depends_on:
  #      - db
  #      - redis
  #    command: uv run celery -A src.worker.app.app worker --loglevel=info
  #
  #  beat:
  #    build:
  #      context: ./backend
  #      dockerfile: Dockerfile
  #    container_name: snippetly-beat
  #    env_file:
  #      - ./backend/.env
  #    depends_on:
  #      - db
  #      - redis
  #    command: uv run celery -A src.worker.app.app beat --loglevel=info

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: snippetly-frontend
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    restart: unless-stopped

volumes: {}

networks:
  default:
    name: snippetly-net
